---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content
  label: Single Pages
  create: none
  match: "*"
- type: directory
  path: content/testimonials
  label: Testimonials
  create: all
  match: "**/*"
- type: directory
  path: content/products
  label: Products
  create: documents
  match: "**/*"
  templates:
  - products
- type: directory
  path: content/blogs
  label: Articles
  create: documents
  match: "**/*"
  templates:
  - articles
upload_dir: hugo
public_path: https://res.cloudinary.com/dlibzi68u/image/upload
front_matter_path: https://res.cloudinary.com/dlibzi68u/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.79.0
